# Generated by Django 6.0.4 on 2026-04-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('revision_previa', 'Revision Previa'), ('revision_verificacion', 'Revision Verificacion'), ('mejoras_solicitadas', 'Mejoras Solicitadas'), ('ultima_revision', 'Ultima Revision'), ('finalizada', 'Finalizada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='agendada', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
