# Generated by Django 6.0.4 on 2026-04-16 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='consultas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
