# Generated by Django 6.0.4 on 2026-04-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_responsables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Estructura dinámica de preguntas y respuestas'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas',
            field=models.TextField(blank=True, help_text='Anotaciones generales sobre la consulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_lab',
            field=models.CharField(choices=[('quimico', 'Químico'), ('biologico', 'Biológico'), ('fisico', 'Físico'), ('clinico', 'Clínico')], default='quimico', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('revision_previa', 'Revisión Previa'), ('revision_verificacion', 'Revisión Verificación'), ('mejoras_solicitadas', 'Mejoras Solicitadas'), ('ultima_revision', 'Última Revisión'), ('finalizada', 'Finalizada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='agendada', max_length=30),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='consultosec/evidencias/%Y/%m/%d/')),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='consultas.consulta')),
            ],
        ),
    ]
