# Generated by Django 6.0.4 on 2026-04-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_options_remove_consulta_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_lab',
            field=models.CharField(choices=[('taller_carpinteria', 'Taller de carpintería'), ('taller_lavado', 'Taller de lavado'), ('lab_mecatronica_basica', 'Laboratorio de mecatrónica básica'), ('lab_mecatronica_avanzada', 'Laboratorio de mecatrónica Avanzada'), ('lab_manufactura_avanzada', 'Laboratorio de manufactura avanzada'), ('lab_electrica', 'Laboratorio de Electrica')], default='taller_carpinteria', max_length=50),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('requisito', models.TextField()),
                ('normativa_aplicable', models.CharField(blank=True, max_length=255, null=True)),
                ('cumple', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcial', 'Parcial'), ('no_evaluado', 'No Evaluado')], default='no_evaluado', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('mejora', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='consultosec/checklists/%Y/%m/%d/')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_checklist', to='consultas.consulta')),
            ],
        ),
    ]
