# Generated by Django 6.0.4 on 2026-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_remove_consulta_checklist_alter_consulta_tipo_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='consultosec/checklists/%Y/%m/%d/'),
        ),
    ]
