# Generated by Django 6.0.4 on 2026-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_checklistitem_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consultosec/checklists/%Y/%m/%d/'),
        ),
    ]
