# Generated by Django 6.0.4 on 2026-04-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_alter_checklistitem_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tipo_lab',
        ),
        migrations.AddField(
            model_name='consulta',
            name='area_laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='consultas.areacatalogo'),
        ),
        migrations.CreateModel(
            name='RequisitoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('normativa_aplicable', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='consultas.areacatalogo')),
            ],
        ),
    ]
