# Generated by Django 6.0.4 on 2026-04-20 22:19

from django.db import migrations
import os
import json
from django.conf import settings

def load_initial_data(apps, schema_editor):
    AreaCatalogo = apps.get_model('consultas', 'AreaCatalogo')
    RequisitoCatalogo = apps.get_model('consultas', 'RequisitoCatalogo')
    
    json_path = os.path.join(settings.BASE_DIR, 'checklist_laboratorios_area_requisito_normativa.json')
    # Si el archivo no existiera por algun motivo en produccion evitamos que crashee
    if not os.path.exists(json_path):
        return
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    for item in data:
        area_name = item['area']
        area_obj, created = AreaCatalogo.objects.get_or_create(nombre=area_name)
        
        for req in item.get('items', []):
            RequisitoCatalogo.objects.get_or_create(
                area=area_obj,
                pregunta=req.get('requisito', ''),
                defaults={'normativa_aplicable': req.get('normativa_aplicable') or ''}
            )

def reverse_initial_data(apps, schema_editor):
    pass # No eliminamos catalogos si se revierte para prevenir borrar datos vitales

class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_areacatalogo_remove_consulta_tipo_lab_and_more'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_initial_data)
    ]
