# Generated by Django 6.0.4 on 2026-04-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_auto_20260420_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha_finalizacion_propuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
