# Generated by Django 6.0.4 on 2026-04-24 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_auto_20260420_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('responsable', models.CharField(max_length=255)),
                ('asistentes', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='consultas.consulta')),
            ],
        ),
    ]
