# Generated by Django 6.0.4 on 2026-04-23 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_auto_20260420_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la mejora')),
                ('justificacion', models.TextField(help_text='Por qué es necesaria esta acción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('implementada', 'Implementada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_mejora', to='consultas.consulta')),
                ('item_checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='consultas.checklistitem')),
            ],
        ),
    ]
