# Generated by Django 6.0.4 on 2026-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_propuestamejora'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestamejora',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechazó la propuesta', null=True),
        ),
    ]
