# Generated by Django 6.0.4 on 2026-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_consulta_fecha_finalizacion_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='categoria',
            field=models.CharField(default='General', max_length=150),
        ),
        migrations.AddField(
            model_name='requisitocatalogo',
            name='categoria',
            field=models.CharField(default='General', max_length=150),
        ),
    ]
