# Generated by Django 6.0.4 on 2026-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_checklistitem_categoria_requisitocatalogo_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='requisitocatalogo',
            options={'ordering': ['id']},
        ),
    ]
