# Generated by Django 6.0.4 on 2026-04-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_capacitacion'),
        ('consultas', '0011_actividad'),
        ('consultas', '0011_alter_checklistitem_options_and_more'),
    ]

    operations = [
    ]
