# Generated by Django 6.0.4 on 2026-04-25 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0012_merge_20260424_1429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='consulta',
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='capacitaciones', to='consultas.consulta'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='laboratorios',
            field=models.ManyToManyField(blank=True, related_name='capacitaciones_asignadas', to='consultas.areacatalogo'),
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='asistentes',
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='capacitaciones_asistidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
