# Generated by Django 6.0.4 on 2026-04-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0013_remove_capacitacion_consulta_capacitacion_consultas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='consultosec/capacitaciones/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('evidencia', 'Evidencia')], default='material', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='consultas.capacitacion')),
            ],
        ),
    ]
