# Generated by Django 6.0.4 on 2026-04-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_capacitacionarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestamejora',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin planificada', null=True),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio planificada', null=True),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='progreso',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance (0-100)'),
        ),
    ]
