# Generated by Django 6.0.4 on 2026-04-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_capacitacionarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='consultosec/checklist_photos/%Y/%m/%d/')),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='consultas.checklistitem')),
            ],
        ),
    ]
