# Generated by Django 6.0.4 on 2026-04-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0015_propuestamejora_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestamejora',
            options={'ordering': ['plazo', 'numero_tarea']},
        ),
        migrations.RemoveField(
            model_name='propuestamejora',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='propuestamejora',
            name='item_checklist',
        ),
        migrations.RemoveField(
            model_name='propuestamejora',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='propuestamejora',
            name='motivo_rechazo',
        ),
        migrations.RemoveField(
            model_name='propuestamejora',
            name='progreso',
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='accion_correctiva',
            field=models.TextField(default='', help_text='Descripción de la acción correctiva'),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='numero_tarea',
            field=models.CharField(default='', help_text='Ej: 1.1, 2.3', max_length=10),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='plazo',
            field=models.CharField(choices=[('corto', 'Corto Plazo'), ('mediano', 'Mediano Plazo'), ('largo', 'Largo Plazo')], default='corto', max_length=10),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='responsables',
            field=models.JSONField(default=list, help_text='Lista de responsables seleccionados'),
        ),
        migrations.AddField(
            model_name='propuestamejora',
            name='s_implementada',
            field=models.CharField(blank=True, choices=[('clasificar', 'Clasificar'), ('ordenar', 'Ordenar'), ('limpiar', 'Limpiar'), ('estandarizar', 'Estandarizar'), ('disciplina', 'Disciplina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propuestamejora',
            name='estado',
            field=models.CharField(choices=[('completado', 'Completado'), ('en_proceso', 'En proceso'), ('requiere_adquisicion', 'Requiere adquisición de insumos o presupuesto por parte del departamento'), ('requiere_instalacion', 'Requiere instalación por parte de mantenimiento')], default='en_proceso', max_length=30),
        ),
        migrations.AlterField(
            model_name='propuestamejora',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propuestamejora',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
